import Glass from './Glass.component';
import {tr} from '../i18n';
export function SkeletonBlock({className=''}:{className?:string}){return <span aria-hidden="true" className={`skeleton-block ${className}`}/>;}
export function OverviewSkeleton({budget=false}:{budget?:boolean}){return <div role="status" aria-label={tr('Caricamento riepilogo')}>
 <div className="overview-grid">{['balance-card','stat-card','stat-card'].map((className,index)=><Glass key={index} className={className}><div className="skeleton-stack"><SkeletonBlock className="skeleton-icon"/><SkeletonBlock className="skeleton-label"/><SkeletonBlock className="skeleton-amount"/><SkeletonBlock className="skeleton-label"/></div></Glass>)}</div>
 {budget&&<Glass className="panel budget-panel"><div className="skeleton-stack"><SkeletonBlock className="skeleton-label"/><SkeletonBlock className="skeleton-amount"/><SkeletonBlock className="skeleton-bar"/></div></Glass>}
 <div className="charts-grid"><Glass className="panel"><div className="skeleton-stack"><SkeletonBlock className="skeleton-label"/><div className="skeleton-chart">{[40,65,50,85,35,70,55,95,45,75,60,80].map((height,index)=><SkeletonBlock key={index} className={`skeleton-column skeleton-column-${height}`}/>)}</div></div></Glass><Glass className="panel"><div className="skeleton-stack"><SkeletonBlock className="skeleton-label"/><SkeletonBlock className="skeleton-donut"/><SkeletonBlock className="skeleton-bar"/><SkeletonBlock className="skeleton-bar"/></div></Glass></div>
 </div>;}
export function CategoriesSkeleton(){return <div role="status" aria-label={tr('Caricamento categorie')} className="category-grid">{[0,1,2].map(index=><Glass key={index} className="category-card"><div className="skeleton-stack"><SkeletonBlock className="skeleton-icon"/><SkeletonBlock className="skeleton-label"/><SkeletonBlock className="skeleton-bar"/><SkeletonBlock className="skeleton-bar"/><SkeletonBlock className="skeleton-bar"/></div></Glass>)}</div>;}
